config/routes.rb
Depot::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
      get :cancel
    end
  end

  get "store/index"

  resources :products, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :carts, :line_items, :orders

  namespace :admin do
    resources :users, :products
    resources :orders, except: [:new, :create]
  end

  root to: 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by_product_id(product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build({product_id: product.id, product_price: product.price}, without_protection: true)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_count
    line_items.inject(0) { |result, item| result + item.quantity }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  load_and_authorize_resource
  skip_authorize_resource only: [:create, :destroy]
  skip_load_resource only: :destroy
  skip_authorization_check only: [:create, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url,
        notice: 'Your cart is currently empty' }
      format.js
      format.json { head :no_content }
    end
  end
end

app/views/carts/_cart.html.erb
<div class="cart_title">Your Cart</div>
<table>
  <%= render(cart.line_items) %>

  <tr class="total_line">
    <td colspan="2">Total</td>
    <td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
  </tr>
</table>

<% if can? :create, Order %>
  <%= button_to "Checkout", new_order_url, method: :get %>
<% else %>
  <%= button_to "Sign in to checkout", new_user_session_path, method: :get %>
<% end %>

<%= button_to 'Empty cart', cart, method: :delete, confirm: 'Are you sure?', remote: true %>

app/views/carts/_form.html.erb
<%= semantic_form_for(@cart) do |f| %>
  <%= f.inputs %>
  <%= f.actions %>
<% end %>

app/views/carts/destroy.js.erb
$('#cart').hide('blind', 1000);

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @carts.each do |cart| %>
    <tr>
      <td><%= link_to 'Show', cart %></td>
      <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
      <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>

<%= link_to 'Edit', edit_cart_path(@product) %> |
<%= link_to 'Back', carts_path %>