config/routes.rb
Depot::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
      get :cancel
    end
  end

  get "store/index"

  resources :products, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :carts, :line_items, :orders

  namespace :admin do
    resources :users, :products
    resources :orders, except: [:new, :create]
  end

  root to: 'store#index', as: 'store'

end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :line_items
  has_many :images, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: :all_blank

  attr_accessible :title, :description, :price, :images_attributes

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  validates :title, length: {minimum: 10, too_short: 'must be at least 10 characters.' }

  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.any?
        errors.add(:base, 'Line items with this product present')
        false
      end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  load_and_authorize_resource
  skip_load_resource only: :index

  # GET /admin/products
  # GET /admin/products.json
  def index
    @search = Product.search(params[:q])
    @products = @search.result.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /admin/products/1
  # GET /admin/products/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /admin/products/new
  # GET /admin/products/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/products
  # POST /admin/products.json
  def create
    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/products/1
  # PUT /admin/products/1.json
  def update
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/products/1
  # DELETE /admin/products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: "An Error Occurred! #{@product.errors[:base].join('; ').capitalize}" }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource

  def show
    @cart = current_cart
    @comment = Comment.new if can? :create, Comment

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end
end

app/views/admin/products/_form.html.erb
<%= semantic_nested_form_for [:admin, @product], :html => {:multipart => true} do |f| %>
  <%= f.inputs do %>
    <%= f.input :title %>
    <%= f.input :description %>

    <%= f.fields_for :images %>
    <%= f.link_to_add "Add an image", :images %>

    <%= f.input :price %>
  <% end %>

  <div class="group navform wat-cf">
    <button class="button" type="submit">
      <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
    </button>
    <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
  	<%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_products_path, :class => "text_button_padding link_button" %>
  </div>
<% end %>

app/views/admin/products/_image_fields.html.erb
<%= f.input :image, as: :file, required: false %>
<%= f.hidden_field :retained_image %>

<% image = f.object %>
<% if image.image_uid %>
  <%= image_tag image.image.thumb('100x100').url %>
<% end %>

<%= f.link_to_remove "Remove this image" %>

app/views/admin/products/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_product_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Product</h2>
    <div class="inner">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Products</h2>

    <%= search_form_for [:admin, @search] do |f| %>
      <%= f.label :title_cont %>
      <%= f.text_field :title_cont %>
      <%= field_set_tag "Price" do %>
        <%= f.label :price_gteq, "≥" %>
        <%= f.number_field :price_gteq, min: 0 %>
        <%= f.label :price_lteq, "≤" %>
        <%= f.number_field :price_lteq, min: 0 %>
      <% end %>
      <%= f.submit %>
    <% end %>

    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">
            <%= sort_link @search, :id, "ID" %>
          </th>
          <th>
            <%= sort_link @search, :title, t("activerecord.attributes.admin_product.title",
                                              :default => t("activerecord.labels.title", :default => "Title")) %>
          </th>
          <th>
            <%= sort_link @search, :price, t("activerecord.attributes.admin_product.price", :default => t("activerecord.labels.price", :default => "Price")) %>
          </th>
          <th><%= sort_link @search, :created_at, t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @products.each do |product| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= product.id %>
          </td>
          <td>
            <%= link_to product.title, admin_product_path(product) %>
          </td>
          <td>
            <%= number_to_currency(product.price) %>
          </td>
          <td>
            <%= product.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_product_path(product) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_product_path(product) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_product_path(product), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
    </div>
    <%= paginate @products %>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Product</h2>
    <div class="inner">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_products_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_product_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_product_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">

        <p>
          <b><%= t("activerecord.attributes.admin_product.title", :default => t("activerecord.labels.title", :default => "Title")) %>:</b>
          <%= @product.title %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.description", :default => t("activerecord.labels.description", :default => "Description")) %>:</b>
          <%= @product.description %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.images", :default => t("activerecord.labels.images", :default => "Images")) %>:</b>
          <div class="images">
            <% @product.images.each do |image| %>
              <%= thumbnail(image.image, '80x96') %>
            <% end %>
          </div>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_product.price", :default => t("activerecord.labels.price", :default => "Price")) %>:</b>
          <%= number_to_currency(@product.price) %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_product_path(@product), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_product_path(@product), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>