config/routes.rb
Depot::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
      get :cancel
    end
  end

  get "store/index"

  resources :products, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :carts, :line_items, :orders

  namespace :admin do
    resources :users, :products
    resources :orders, except: [:new, :create]
  end

  root to: 'store#index', as: 'store'

end

app/models/user.rb
class User < ActiveRecord::Base

  before_validation :set_default_role

  has_many :orders
  has_many :comments

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  attr_accessor :accessible

  ROLES = %w[admin user]

  validates :name, :role, presence: true
  validates :role, inclusion: { in: ROLES }

  private

    def set_default_role
      self.role = "user" if role.nil?
    end

    def mass_assignment_authorizer(role = :default)
      super + (accessible || [])
    end
end

app/controllers/admin/users_controller.rb
include Admin::UsersHelper

class Admin::UsersController < Admin::BaseController
  load_and_authorize_resource
  skip_load_and_authorize_resource only: :create

  # GET /admin/users
  # GET /admin/users.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new
    @user.accessible = [:role] if can? :set_role, @user
    @user.assign_attributes(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    @user.accessible = [:role] if can? :set_role, @user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def roles_collection
    User::ROLES.map { |role| [role.humanize, role] }
  end

  def role(user)
    user.try(:role) ? user.role : User::ROLES.last
  end
end

app/views/admin/users/_form.html.erb
<%= semantic_form_for([:admin, @user]) do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :role, include_blank: false, selected: role(@user), collection: roles_collection if can?(:set_role, User) %>
    <%= f.input :password, hint: :new_password %>
    <%= f.input :password_confirmation, required: true %>
  <% end %>

  <div class="group navform wat-cf">
    <button class="button" type="submit">
      <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
    </button>
    <span class="text_button_padding"><%= t("web-app-theme.or", :default => "or") %></span>
    <%= link_to t("web-app-theme.cancel", :default => "Cancel"), admin_users_path, :class => "text_button_padding link_button" %>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> User</h2>
    <div class="inner">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Users</h2>
    <div class="inner">
      <table class="table">
        <tr>
          <th class="first">ID</th>
          <th>
            <%= t("activerecord.attributes.admin_user.name", :default => t("activerecord.labels.name", :default => "Name")) %>
          </th>
          <th>
            <%= t("activerecord.attributes.admin_user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
          </th>
          <th>
            <%= t("activerecord.attributes.admin_user.role", :default => t("activerecord.labels.role", :default => "Role")) %>
          </th>
          <th><%= t("web-app-theme.created_at", :default => "Created at")  %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @users.each do |user| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= user.id %>
          </td>
          <td>
            <%= link_to user.name, admin_user_path(user) %>
          </td>
          <td>
            <%= link_to user.email, admin_user_path(user) %>
          </td>
          <td>
            <%= user.role.humanize %>
          </td>
          <td>
            <%= user.created_at %>
          </td>
          <td class="last">
            <%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path(user) %> |
            <%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_admin_user_path(user) %> |
            <%= link_to "#{t("web-app-theme.delete", :default => "Delete")}", admin_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
          </td>
        </tr>
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
    </ul>
  </div>
  <div class="content">
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  User</h2>
    <div class="inner">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", admin_users_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_admin_user_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", admin_user_path %></li>
    </ul>
  </div>
  <div class="content">
    <div class="inner">

        <p>
          <b><%= t("activerecord.attributes.admin_user.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @user.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.email", :default => t("activerecord.labels.email", :default => "Email")) %>:</b>
          <%= @user.email %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.role", :default => t("activerecord.labels.role", :default => "Role")) %>:</b>
          <%= @user.role %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.sign_in_count", :default => t("activerecord.labels.sign_in_count", :default => "Sign in count")) %>:</b>
          <%= @user.sign_in_count %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.current_sign_in_at", :default => t("activerecord.labels.current_sign_in_at", :default => "Current sign in at")) %>:</b>
          <%= @user.current_sign_in_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.last_sign_in_at", :default => t("activerecord.labels.last_sign_in_at", :default => "Last sign in at")) %>:</b>
          <%= @user.last_sign_in_at %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.current_sign_in_ip", :default => t("activerecord.labels.current_sign_in_ip", :default => "Current sign in ip")) %>:</b>
          <%= @user.current_sign_in_ip %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.admin_user.last_sign_in_ip", :default => t("activerecord.labels.last_sign_in_ip", :default => "Last sign in ip")) %>:</b>
          <%= @user.last_sign_in_ip %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_admin_user_path(@user), :class => "button" %>
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), admin_user_path(@user), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>
    </div>
  </div>
</div>