config/routes.rb
Depot::Application.routes.draw do

  devise_for :users, skip: :registrations

  devise_scope :user do
    resource :registration,
      only: [:new, :create, :edit, :update],
      path: 'users',
      path_names: { new: 'sign_up' },
      controller: 'devise/registrations',
      as: :user_registration do
      get :cancel
    end
  end

  get "store/index"

  resources :products, only: [:show] do
    resources :comments, only: [:new, :create]
  end

  resources :carts, :line_items, :orders

  namespace :admin do
    resources :users, :products
    resources :orders, except: [:new, :create]
  end

  root to: 'store#index', as: 'store'

end

app/views/layouts/_user_bar.html.erb
<div id="user_bar">
  <% if user_signed_in? %>
    Signed in as <span id="name"><%= current_user.name %></span>.<br />
    <%= link_to "Edit profile", edit_user_registration_path %><br />
    Not you?
    <%= link_to "Sign out", destroy_user_session_path, method: 'delete' %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag 'web_app_theme/web_app_theme' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Depot</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><%= link_to t("web-app-theme.profile", :default => "Profile"), edit_admin_user_path(current_user) %></li>
          <li><%= link_to t("web-app-theme.signout", :default => "Sign out"), destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"> <li class="<%= controller.controller_path == 'admin/users' ? 'active' : '' %>"><a href="<%= admin_users_path %>">Users</a></li> <li class="<%= controller.controller_path == 'admin/products' ? 'active' : '' %>"><a href="<%= admin_products_path %>">Products</a></li> <li class="<%= controller.controller_path == 'admin/orders' ? 'active' : '' %>"><a href="<%= admin_orders_path %>">Orders</a></li></ul>
      </div>
    </div>
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Depot.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <!--[if IE 6]><%= stylesheet_link_tag 'ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'ie7' %><![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
  <div id="banner">
    <%= link_to image_tag("logo.png"), store_path %>
    <%= @page_title || "Pragmatic Bookshelf" %>
  </div>
  <div id="columns">
    <div id="side">
      <span id="datetime"><%= date_time %></span>

      <%= render partial: 'layouts/user_bar' %>

      <ul>
        <li><%= link_to 'Store', store_path %></li>
        <li><a href="#">Contact</a></li>
      </ul>

      <ul>
        <% if can? :read, Product %>
          <li><%= link_to 'Products', admin_products_path %></li>
        <% end %>
        <% if can? :read, User %>
          <li><%= link_to 'Users', admin_users_path %></li>
        <% end %>
        <% if can? :read, Order %>
          <li><%= link_to 'Orders', orders_path %></li>
        <% end %>
      </ul>

      <% if @cart %>
        <%= hidden_div_if(current_cart.line_items.empty?, id: 'cart') do %>
          <%= render current_cart %>
        <% end %>
      <% end %>
    </div>
    <div id="main">
      <%= render partial: 'shared/show_flash' %>
      <%= yield %>
    </div>
  </div>
</body>
</html>